version: 2.1
orbs:
  node: circleci/node@4.7.0
workflows:
  build_test: # 任意の名前をお選びください。
    jobs:
      - build_and_test

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run test
      - run:
          command: yarn build
          name: Run build
      - persist_to_workspace:
          root: ~/project
          paths: .